### ISSUE TITLE
GenerateLowHighImages not implemented

### ISSUE THREAD

**Issue by gunta** [GammaUNC/FasTC#17]
Hi, while trying to convert a PVRTC I get the following error:

```
Assertion failed: (!"Implement me!"), function GenerateLowHighImages, file /Users/a12907/Hayabusa/FasTC/src/PVRTCEncoder/src/Compressor.cpp, line 553.
[1]    10010 abort      CLTool/tc 
```

**Comment by Mokosha** [comment]
Our PVRTC compressor doesn't support alpha at the moment. If possible, send us the image that you'd like to compress and we can see what we can do.

**Comment by gunta** [comment]
@Mokosha Yes :)

**Comment by Mokosha** [comment]
Alright, we'll take a look.
