### ISSUE TITLE
DXT5 compressor seems broken

### ISSUE THREAD

**Issue by guycalledfrank** [GammaUNC/FasTC#22]
I checked DXT1, and it produced good results. Then tried DXT5 and got a weird repeating block pattern:
![15](https://cloud.githubusercontent.com/assets/7008423/18522628/78b8baf2-7ab9-11e6-82fb-00e404af0df1.png)
To save the DXT5, I used GetCompressedData/Size and attached the header myself. Also checked compressed data in a hex editor, and it's predictably full of repeating patterns.

**Comment by guycalledfrank** [comment]
OK, I found the problem: 
https://github.com/GammaUNC/FasTC/blob/e2b741d977f1a5ee846dcd45c6f4a93945e9198f/DXTEncoder/src/Compressor.cpp#L91

You must increment by 16, not 8, for DXT5, we have 8 alpha + 8 color bytes total.

You can see that's also what they do in stb example:
https://github.com/nothings/stb/blob/8aa9afb30e6aeb129235829c5e0ed41b6562ea37/tests/caveview/stb_gl.h#L563

**Comment by Mokosha** [comment]
Nice catch, thanks!
