### ISSUE TITLE
Void-Extend blocks handling ASTC

### ISSUE THREAD

**Issue by DavidPeicho** [GammaUNC/FasTC#25]
Looking at the ASTC Decompressor, I did not find where you handle void-extent blocks.
Looking at the specifications, I see that void-extent blocks do not have the same layout as "normal" blocks. Can you use your decompressor on normal maps ? because a lot of them have some void-extent blocks, and I am wondering whether you handle it in another way or not.

**Comment by Mokosha** [comment]
Currently it doesn't handle it mostly because the test images I used didn't have any. Certainly a good thing to do (although it shouldn't be very difficult -- void extent blocks are pretty easy to decode).
