### ISSUE TITLE
ASTC decompression gives fragments near image bounds with 6x6 blocks

### ISSUE THREAD

**Issue by DavidPeicho** [GammaUNC/FasTC#27]
I tried your decompressor on several ASTC files encoded using the ARM encoder, using the following command options: 3.56 -medium

You can see below the expected result and what I obtained:

_ARM Decoder output_
![Image obtained using the ARM decoder](https://cloud.githubusercontent.com/assets/8783766/19132425/ac8bbae6-8b53-11e6-80b7-8b65d6148910.png)

_FasTC output_
![Image obtained using FasTC](https://cloud.githubusercontent.com/assets/8783766/19132359/60aba546-8b53-11e6-9d38-6a5474636d72.png)

The white squares are not important, they appear because you did not provide the void-extent block decompression, that is not the point here.

The major problem comes on the left side of the image, where we can see some pink fragments. These fragments are quite often present, even on other images, and always on the left border. I did not have time to dig it a lot, but my intuition is that this is caused when you are writing your pixel to the out buffer.

Another thing that should be pointed out, you can see that the top of the image is also different from what was expected (there is also an error block). I tried to look around a bit for this, and I have the impression that your raw data is inconsistent. This second problem also appeared on several images.

If I have time to look around, I will try to find why these two issues appear and make a pull request.

**Comment by Mokosha** [comment]
Thanks for the test case! Can you tell me what settings you used with the ASTC encoder so that I can try and reproduce it on my end (also do you have the source image?)

**Comment by DavidPeicho** [comment]
Sure, I used the "3.56" (6x6 block) and "-medium" command line options, nothing else.

The source image is:
![normal](https://cloud.githubusercontent.com/assets/8783766/19144038/b8e16c4c-8ba7-11e6-988a-412e1d8bda89.png)

**Comment by DavidPeicho** [comment]
I found something interesting, the color on the left border depends on the color of the right border. I tried to put some yellow, and the fragments on the left were all yellow.
