### ISSUE TITLE
Regression in f43e934e

### ISSUE THREAD

**Issue by wmatyjewicz** [GammaUNC/FasTC#30]
f43e934e seems to introduce artifacts in the compressed output and, in general, decrease PSNR. 
Compressing the below picture:
![picture](https://cloud.githubusercontent.com/assets/4330462/26548542/00e5b45e-4475-11e7-9379-5a129274784b.png)
with:
`tc -f DXT1 -d picture.ktx picture.png`
and then decompressing it with:
`decomp picture.ktx decomp.png`
generates output with rectangular black artifacts:
![decomp](https://cloud.githubusercontent.com/assets/4330462/26548552/0a00cf42-4475-11e7-976f-885a04bf7e9e.png)

Reverting this commit makes the artifacts disappear.

**Comment by Mokosha** [comment]
I remember making this change for a reason but I have no idea what that is anymore. =/
