### ISSUE TITLE
about pvrtc compression quality

### ISSUE THREAD

**Issue by mhq7075** [GammaUNC/FasTC#31]
It's the only code i found to compress pvrtc tex after a long search, and it's easy to use.but  the compressed  texture looks worse than pvrtextool, shown in this image http://tinypic.com/view.php?pic=14tvdkj&s=9#.WcAjfYSGOUk, the left is compressed with fastc, the right is pvrtextool, the difference is very obvious on cheek. Is this a known issues?  any plan to solve this?

**Comment by Mokosha** [comment]
We're aware of the issue. Unfortunately, this project was mostly research code and I wouldn't recommend it for production use. We're likely not going to devote too much time to improving the speed/quality, either. We'll still support it through minor bug fixes, but improving the quality (barring some easily quantifiable bug) is probably not going to happen. For reference, though, the best way to improve the PVRTC quality is to do an iterative refinement of the endpoints and indices of each block. Right now we select the endpoints and then the indices and call it a day, but that's not a great way to do it.

Patches are gladly accepted, though!
