### ISSUE TITLE
Useless help

### ISSUE THREAD

**Issue by pps83** [GammaUNC/FasTC#32]
I don't see a way to create output file. `tc -h` outputs:

```
Usage: tc [OPTIONS] imagefile

        -h|--help       Print this help.
        -v              Verbose mode: prints out Entropy, Mean Local Entropy, and MSSIM
        -f <fmt>        Format to use. Either "BPTC", "ETC1", "DXT1", "DXT5", or "PVRTC". Default: BPTC
        -l              Save an output log.
        -d <file>       Specify decompressed output (default: basename-<fmt>.png)
        -nd             Suppress decompressed output
        -q <quality>    Set compression quality level. Default: 50
        -n <num>        Compress the image num times and give the average time and PSNR. Default: 1
        -simd           Use SIMD compression path
        -t <num>        Compress the image using <num> threads. Default: 1
        -a              Compress the image using synchronization via atomic operations. Default: Off
        -j <num>        Use <num> blocks for each work item in a worker queue threading model. Default: (Blocks / Threads)
```

There is no way to produce output?
It would be **extremely** helpful if you provided images (in github repo or external links) and command line params used for both tools you used to get comparison results between FastTC and PVRTexTool (see http://gamma.cs.unc.edu/FasTC/).
In my case I try to run some defaults that this help provides and FastTC is like 10-20 times slower for me and doesn't even produce any output.

**Comment by Mokosha** [comment]
There is no way to produce compressed output.

This library is a research project and so `tc` is really only a command line tool that was used for testing various compression options and then visualizing the output (via the `-f` flag). For a production-level compressor that supports PVRTC, I'd recommend looking at [basis](https://github.com/BinomialLLC/basis_universal).
