### ISSUE TITLE
file loss

### ISSUE THREAD

**Issue by FarawayRay** [GammaUNC/FasTC#33]
hi,the project include some .h file and i cant find
such as:BC7Config.h BC7Compressor.h and avpcl.h

**Comment by FarawayRay** [comment]
i make ETCEncoder to lib，the application while shutdown when i compress.
`	std::string _strfile = "F:\\all.png";
	std::vector<unsigned char> _image;
	unsigned _width, _height;

	unsigned _error = lodepng::decode(_image, _width, _height, _strfile, LCT_RGB, 8);
	if (_error)
	{
		return 0;
	}
	std::cout << _image.size() << ":" << _width << ":" << _height << std::endl;
	uint8 *_imageinbuffer(new uint8(_image.size()));
	memcpy(&_imageinbuffer, &_image, sizeof(_image));
	uint8 *outBuffer = new uint8(sizeof(_image));
	std::unique_ptr<FasTC::CompressionJob> pCompressJob(new FasTC::CompressionJob(FasTC::eCompressionFormat_ETC1, 
		(const uint8*)_imageinbuffer,
		outBuffer, 
		_width, 
		_height));
	DXTC::CompressImageDXT1(*pCompressJob);`

shutdown from this
`  void ExtractBlock(const uint32* inPtr, uint32 width, uint8* colorBlock)
  {
    for (int j = 0; j < 4; j++)
    {
      memcpy(&colorBlock[j * 4 * 4], inPtr, 4 * 4);
      inPtr += width;
    }
  }`
I dont know where is error

**Comment by FarawayRay** [comment]
thanks for your code，i had finish this

**Comment by Mokosha** [comment]
I'm unclear about what the problem or the solution was. For the .h files, some of those are generated through CMake's configuration process. If you have any other questions feel free to reopen a new issue.
